#!/system/bin/sh

# Pre-boot scripts that executed
# after File System mounts, and 
# before booting Android


MODS="/sdcard/lab/android/mods"
SYSTEM="/sbin/.magisk/mirror/system"
VENDOR="/sbin/.magisk/mirror/vendor"


# Remount as RW
/data/xbin/remount-rw

# AdBlock
cp -f /sdcard/lab/android/etc/hosts.final $SYSTEM/etc/hosts

# Custom Fonts
# cp -f $MODS/fonts/* $SYSTEM/fonts/
# chmod 644 $SYSTEM/fonts/*