#!/system/bin/sh

{
    while [ "$(getprop sys.boot_completed)" != "1" ]
        do sleep 3
        done
    /system/xbin/bash /system/xbin/post-boot autorun &> /sdcard/lab/android/log/post-boot.log
} &