#!/data/bin/bash

## Manage adblock via /etc/hosts
## Author: Seff P
## Version: 20200825

source check-root

source set-dir
source set-color

SYS_HOSTS="/system/etc/hosts"
CURL="/system/bin/curl"
MODE=$2
[ $MODE ] || MODE="-#"

case "$1" in
 -e|e*)
    echo -n "$(logdate) Enabling Adblock "
    if ! mount | grep -q $SYS_HOSTS
    then
        mount -o bind $ETC/hosts.final $SYS_HOSTS
        DONE
    else
        SKIP
    fi
    ;;
  
 -d|d*)
    echo -n "$(logdate) Disabling Adblock "
    if mount | grep -q $SYS_HOSTS
    then
        umount $SYS_HOSTS
        DONE
    else
        SKIP
    fi
    ;;
  
 -u|u*)
    if ! mount | grep -q $SYS_HOSTS
    then
        echo -e "$(logdate) Adblock is disabled. Update aborted!"
        exit 1
    fi
    
    echo -e "$(logdate) Updating Adblock $(BEGIN)"
    CUR_BYTES=$(cat $VAR/hosts.comm_bytes)
    echo -ne "$(logdate) Downloading update "
    NEW_BYTES=$($CURL -Is --insecure --connect-timeout 5 https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts | busybox awk '/Content-Length/ {printf $2}')

    if [[ "$CUR_BYTES" == "$NEW_BYTES" ]]
        then SKIP
        date > $VAR/adblock-update.last_run
    elif [ -z "$NEW_BYTES" ]
        then FAIL
    else
        PREV_RECORDS=$(cat $VAR/hosts.comm_records)
        $CURL --insecure https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts -o $ETC/hosts.comm $MODE
        echo -n $NEW_BYTES > $VAR/hosts.comm_bytes
        CUR_RECORDS=$(grep -c ^0 $ETC/hosts.comm)
        echo $CUR_RECORDS > $VAR/hosts.comm_records
        NEW_RECORDS=$(($CUR_RECORDS - $PREV_RECORDS))
        date > $VAR/adblock-update.last_run
        echo -e "Database version: $(grep  "# Date:" $ETC/hosts.comm | cut -d' ' -f3-5)\nNew records: $NEW_RECORDS" | termux-notification --title "Adblock Database Updated!"  --id adblock-update
        COMM_UPED=true
        DONE
    fi

    echo -ne "$(logdate) Updating user entries "
    if ! md5sum -c $VAR/hosts.user_md5 &> /dev/null
        then USER_UPED=true
        md5sum $ETC/hosts.user > $VAR/hosts.user_md5
        DONE
    else
        SKIP
    fi
    
    if ! md5sum -c $VAR/hosts.excludes_md5 &> /dev/null
        then EXCL_UPED=true
        md5sum $ETC/hosts.excludes > $VAR/hosts.excludes_md5
    fi
    
    echo -en "$(logdate) Processing excludes "
    if [[ "$COMM_UPED" || "$EXCL_UPED" ]]
        then
        for EXCLUDE in $(cat $ETC/hosts.excludes)
            do
            sed -i "/$EXCLUDE/d" $ETC/hosts.comm
        done
        DONE
    else
        SKIP
    fi
    echo -en "$(logdate) Applying new update "
    if [[ "$COMM_UPED" || "$USER_UPED" || "$EXCL_UPED" ]]
        then
        cp -f $ETC/hosts.comm $ETC/hosts.final
        cat $ETC/hosts.user >> $ETC/hosts.final
        DONE
    else
        SKIP
    fi
    
    echo -e "$(logdate) Community update: $(grep  "^# Date:" $ETC/hosts.comm | cut -d' ' -f3-5)"
    echo -e "$(logdate) Community entries:$(grep  "^# Number of unique domains" $ETC/hosts.comm | cut -d':' -f2)"
    
    USER_REC=$(grep -c ^0 $ETC/hosts.user)
    echo -e "$(logdate) User entries: $USER_REC"
    echo -e "$(logdate) Updating Adblock $(DONE)"
    ;;
 *)
    echo "Usage: $(basename $0) [-u|update | -e|enable -d|disable]"
    ;;
esac