#!/data/bin/bash

## Update App from given APK file URL
## Author: Seff P.
## Version: 2.0.3 20210630

source set-dir
source set-prompt
source set-log

APP_ID="apk-update"
CONFD="$ETC/${APP_ID}"
APK_DIR="/sdcard/Backups/apps"
LOG_FILE="$LOG/${APP_ID}.log"
TMP="/data/local/tmp/"

read_conf () {
    source $1
    APK_URL="$VAR/${APP_ID}/$PKG_ID.url"
}

checkUpdate () {
    echo -n "Checking ${APP_NAME} update "
    APK_URL_OLD=$(cat $APK_URL 2> /dev/null)
    APK_URL_NEW=$(/system/bin/curl -sk --connect-timeout 10 -m 10 $ASSET_URL | grep -o "$PATTERN" | head -1)
    if [[ "$APK_URL_NEW" == "$APK_URL_OLD" ]]
        then OK
        rm -f $BUCKET
        return 2
    elif [[ -z $APK_URL_NEW ]]
        then FAIL
        return 1
    else
        APK_NAME=$(basename $APK_URL_NEW)
        termux-notification --title "${APP_NAME} update available" --content "$APK_NAME" --id $PKG_ID --icon info
        UPDATED
        return 0
    fi
}

installUpdate () {
    PKG_VERSION_CURR=$(dumpsys package $PKG_ID | awk -F "=" '/versionName/ {print $2}')
    echo "Current version: $PKG_VERSION_CURR"
    echo "Downloading $APP_NAME update..."
    echo $APK_DIR/$APK_NAME
    wget -c -t 0 -T 10 $APK_URL_NEW -O $APK_DIR/$APK_NAME
    echo "Updating ${APP_NAME} $(BEGIN)"
    cp -f $APK_DIR/$APK_NAME $TMP/
    if apk-install $TMP/$APK_NAME
        then
        echo $APK_URL_NEW > $APK_URL
        PKG_VERSION_NEW=$(dumpsys package $PKG_ID | awk -F "=" '/versionName/ {print $2}')
        termux-notification --title "${APP_NAME} is successfully updated" \
        --content "from version $PKG_VERSION_CURR to $PKG_VERSION_NEW" --id $PKG_ID --icon file_download
        echo "Updated version: $PKG_VERSION_NEW"
        file-log "$APP_NAME updated to version $PKG_VERSION_NEW"
        echo "Updating ${APP_NAME} $(DONE)"
    else
        termux-notification --title "${APP_NAME} update failed" --content "$APK_NAME" --id $PKG_ID --icon error
        file-log "Updating ${APP_NAME} failed"
        echo "Updating ${APP_NAME} $(FAIL)"
    fi
    rm -f $TMP/$APK_NAME
}

case $1 in
    -c | c* )
        for CONF in $CONFD/*.conf
            do read_conf $CONF
            checkUpdate
        done
        ;;
    -u | u* )
        check-root && \
        for CONF in $CONFD/*.conf
            do read_conf $CONF
            checkUpdate && \
            installUpdate
        done
        ;;
    *)
        echo "Usage: -c|check | -u|update"
        exit 1
        ;;
esac