#!/data/bin/bash

# Install APK and splits using native pm
# Author: Seff Parker
# Version: 0.0.2 20210630

source check-root
source set-prompt


if [[ $1 ]] && APKS=$(ls $*)
then
    SESSION_ID=$(pm install-create -d --dont-kill | grep -o "[0-9]*")
    for APK in $APKS
        do
        echo "Processing APK $APK"
        BYTES=$(stat -c %s $APK)
        APK_NAME=$(basename $APK)
        cat $APK | pm install-write -S $BYTES $SESSION_ID ${APK_NAME} || ABORT_ALL
    done
    echo "Write complete. Install begin..."
    pm install-commit $SESSION_ID && DONE "Install completed" || FAIL "Install failed"
else
    ABORT "Input error"
fi
exit $CODE