#!/data/bin/bash

## Update Termux APT packages
## Author: Seff P
## Version: 1.0.1 20210604

source set-dir
source set-prompt
BASENAME=$(basename $0)
BUCKET="$VAR/status-widget/bucket/${BASENAME}"


case $1 in
 -r|r*)
    CURR_TS=$(date +%s)
    PKG_UPDATE_TS=$(date +%s -r /data/data/com.termux/files/usr/var/log/apt/history.log)
    let PKG_UPDATE_AGE=$CURR_TS-$PKG_UPDATE_TS
    let PKG_UPDATE_THR=$(cat $ETC/${BASENAME}.remind_days)*86400
    let PKG_UPDATE_AGE_DAYS=$PKG_UPDATE_AGE/86400
    if [ $PKG_UPDATE_AGE -gt $PKG_UPDATE_THR ]
    then
        termux-notification --title "APT packages are not updated recently!" --content "Last updated $PKG_UPDATE_AGE_DAYS days ago" --icon warning
        echo "APT packages last updated $PKG_UPDATE_AGE_DAYS days ago" > $BUCKET
    fi
    echo "APT packages last updated $PKG_UPDATE_AGE_DAYS days ago"
    ;;
    
 "")
    if check-root &> /dev/null
        then echo "${BASENAME} cannot run as root $(FAIL)"
        exit 1
    fi
	if check-ping
	then
	    echo -e "${BASENAME} $(BEGIN)"
	    apt update
	    apt full-upgrade -y
	    apt autoremove -y
	    apt list --installed > $VAR/${BASENAME}.installed_pkg
	    rm -f $BUCKET
	    echo -e "${BASENAME} $(DONE)"
	else
	    echo -e "${BASENAME} $(FAIL)"
	fi
    ;;
    
 *)
    echo "Usage $(basename $0) [-r|report]"
    ;;
esac