#!/data/bin/bash

## Auto-stop media playback and turn off Bluetooth
## Author: Seff P
## Version: 4.0.1 20210214

source /sdcard/lab/android/etc/bashrc.root
source check-root
source set-dir
source set-prompt

PID_FILE=$RUN/audio-sleep.pid
STATUS=$VAR/audio-sleep.left
EXTEND=30
[[ -f $ETC/audio-sleep.conf ]] && source $ETC/audio-sleep.conf

daemon_run () {
    termux-wake-lock
    for ((MIN=$1; MIN > 0; MIN--))
    do
        logdate "DEBUG: $MIN minutes left to sleep"
        echo -n ${MIN} > ${STATUS}
        timeout 1 termux-notification --alert-once --ongoing --id audio-sleep \
        -t "Audio player will stop in $MIN minutes" \
        --button1 "Extend ${EXTEND}m" \
        --button1-action "su -c '$0 +${EXTEND}'"\
        --button2 "Abort" \
        --button2-action "su -c '$0 0'"
        sleep 60
    done
    echo -n 0 > ${STATUS}
    termux-notification --content "Audio player is being stopped" \
        --ongoing --id audio-sleep \
        --button1 "Extend ${EXTEND}m" \
        --button1-action "su -c '$0 ${EXTEND}'"
    echo "DEBUG: Audio player is being stopped" 
    ORG_VOL=$(termux-volume | awk '/music/ {getline; print $2+0}')
    for VOL in $(seq $ORG_VOL | sort -nr)
        do
        termux-volume music $VOL
        logdate "DEBUG: Current volume is $VOL"
        sleep 10
        done
    input keyevent 86 # stop media
    logdate "DEBUG: Restoring volume back to $ORG_VOL"
    termux-volume music $ORG_VOL # restore volume
    /system/bin/svc bluetooth disable
    /system/bin/svc data disable
    /system/bin/svc wifi disable
    rm -fv $PID_FILE $STATUS
    termux-notification-remove audio-sleep
    termux-wake-unlock
    logdate "DEBUG: Exiting"
}

print_usage () {
    echo "USAGE:"
    echo -e "\t`basename $0` <minutes-to-sleep>"
    echo -e "\t`basename $0` +<minutes-to-extend>"
    echo -e "\t`basename $0` 0 <zero-to-abort>"
    exit 1
}

daemon_stop () {
    echo -n "Aborting audio-sleep "
    if daemon -t -p $PID_FILE -c $0
    then
        PID=$(cat $PID_FILE)
        busybox pkill -9 -P $PID &> /dev/null
        daemon -k -p $PID_FILE -c $0
        termux-wake-unlock
        termux-notification-remove audio-sleep
        rm -f $STATUS $PID_FILE
        DONE
    else
        termux-notification-remove audio-sleep
        OK
    fi
}

daemon_start () {
    echo -ne "Setting sleep timer to $1 minutes "
    daemon -s -p $PID_FILE -c $0 -a "run $1"
    DONE
}

case $1 in
    run)
        [[ $2 -gt 0 ]] && daemon_run $2 || print_usage
        ;;
    0)
        daemon_stop
        ;;
    +[1-9]*)
        MIN_LEFT=$(cat $STATUS 2> /dev/null)
        let MIN=${MIN_LEFT}${1}
        daemon_stop &> /dev/null
        daemon_start $MIN
        ;;
    [1-9]*)
        daemon_stop &> /dev/null
        daemon_start $1
        ;;
    *)
        print_usage
        ;;
esac