#!/data/bin/bash

## Auto-stop media playback and turn off Bluetooth
## Author: Seff P
## Version: 20200816


source check-root
source set-dir
source set-color
source /.bashrc

PID_FILE=$RUN/audio-sleep.pid
STATUS=$VAR/audio-sleep.left
BT_OFF=8 # may vary with chipset

sleep_daemon () {
    termux-wake-lock
    for ((MIN=$1; MIN > 0; MIN--))
    do
        echo -n ${MIN} > ${STATUS}
        termux-notification --alert-once --ongoing --id audio-sleep \
        -t "Audio player will stop in $MIN minutes" \
        --button1 "Extend 30m" \
        --button1-action "su -c '$0 +30'"\
        --button2 "Abort" \
        --button2-action "su -c '$0 0'" \
        &
        sleep 60
    done
    echo -n 0 > ${STATUS}
    termux-notification --content "Audio player is being stopped" \
        --ongoing --id audio-sleep \
        --button1 "Extend 30m" \
        --button1-action "su -c '$0 30'"
    CUR_VOL=$(termux-volume | awk '/music/ {getline; print $2+0}')
    for VOL in $(seq $CUR_VOL | sort -nr)
        do
        termux-volume music $VOL
        sleep 5
        done
    input keyevent 86 # stop media
    termux-volume music $CUR_VOL # restore volume
    service call bluetooth_manager $BT_OFF &> /dev/null # turn off bluetooth
    rm -f $PID_FILE $STATUS
    termux-notification-remove audio-sleep
    termux-wake-unlock
    pkill com.termux
}

print_usage () {
    echo "USAGE:"
    echo -e "\t`basename $0` <minutes-to-sleep>"
    echo -e "\t`basename $0` +<minutes-to-sleep>"
    echo -e "\t`basename $0` 0 <zero-to-abort>"
    exit 1
}

sleep_stop () {
    echo -n "Aborting audio-sleep "
    if kill-process $0 $PID_FILE check-only
    then
        termux-notification-remove audio-sleep
        termux-wake-unlock
        kill-process $0 $PID_FILE
        rm -f $STATUS
        DONE
    else
        SKIP
    fi
}

sleep_start () {
    echo -ne "Setting sleep timer to $1 minutes "
    sleep_stop &> /dev/null
    sleep_daemon $1 &> /dev/null &
    echo $! > $PID_FILE
    DONE
}

case $1 in
    0)
        sleep_stop
        ;;
    +[1-9]*)
        MIN_LEFT=$(cat $STATUS 2> /dev/null)
        let MIN=${MIN_LEFT}${1}
        sleep_stop &> /dev/null
        sleep_start $MIN
        ;;
    [1-9]*)
        sleep_start $1
        ;;
    *)
        print_usage
        ;;
esac