#!/data/bin/bash

# Basic charging control and status notification
# Author: Seff P.
# Version: 20200829

source check-root
source set-dir
source $ETC/bcc.conf

chmod u+w $CHARGE_FILE $CURR_LIMIT_FILE

set_cycle () {
    MODE="Cycle"
    STOP_LEVEL=$CYCLE_STOP_LEVEL
    RESUME_LEVEL=$CYCLE_RESUME_LEVEL
    CURRENT_LIMIT=$CYCLE_CURRENT_LIMIT
    BUTTON1_TEXT="Supercharge 🚀"
    BUTTON1_ACTION="su -c 'pkill -l USR2 -f $0'"
    SETTLED=false
    logdate "Set to Cyclecharge mode" >> $BCC_LOG
}

set_super () {
    MODE="Super"
    STOP_LEVEL=$SUPER_STOP_LEVEL
    RESUME_LEVEL=$SUPER_RESUME_LEVEL
    CURRENT_LIMIT=$SUPER_CURRENT_LIMIT
    BUTTON1_TEXT="Cyclecharge ♻️"
    BUTTON1_ACTION="su -c 'pkill -l USR1 -f $0'"
    IS_DISABLED=true
    SETTLED=false
    logdate "Set to Supercharge mode" >> $BCC_LOG
}

hide_status () {
    SHOW_STATUS=false
    termux-notification-remove bcc
    logdate "Notification disabled for this cycle" >> $BCC_LOG
}

daemon_run () {
trap set_cycle USR1
trap set_super USR2
trap hide_status HUP

while true
    do
    LEVEL=$(grep . $LEVEL_FILE)
    if grep -Eq "^Charging|Not charging" $STATUS_FILE
        then # being charged or paused
        LINE_VOLT=$(awk '{print $1/1000000 "v"}' $LINE_VOLT_FILE)
        CURR=$(awk '{if ($1 >= 1000000) print $NF/1000000 "A"; else print $1/1000 "mA"}' $CURR_R_FILE)
        TEMP=$(awk '{print $1/10}' $TEMP_FILE)
        
        if $INIT
            then # prepare for init
            echo 0 > $CURR_UNLIMIT_FILE
            WAS_CHARGING=true
            LEVEL_INIT=$LEVEL
            TIME_INIT=$(date +%s)
            INIT=false
            SETTLED=false
            CURR_UNLIMIT_TEXT="(calibrating)"
            logdate "${MODE}charging initialized at $LEVEL%" >> $BCC_LOG
            
        elif ! $SETTLED
            then # calculate max current
            sleep $SLEEP_SHORT
            sleep $SLEEP_SHORT
            echo $CURRENT_LIMIT > $CURR_LIMIT_FILE
            sleep 1
            CURR=$(awk '{if ($1 >= 1000000) print $NF/1000000 "A"; else print $1/1000 "mA"}' $CURR_R_FILE)
            # CURR_UNLIMIT=$(sort -nr $CURR_UNLIMIT_FILE $CURR_W_FILE | head -1)
            # CURR_UNLIMIT_TEXT=$(echo $CURR_UNLIMIT | awk  '{printf "(max. "; if ($1 >= 1000000) print $NF/1000000 "A)"; else print $1/1000 "mA)"}')
            CURR_UNLIMIT_TEXT=$(awk '{printf "(max. "; if ($1 >= 1000000) print $NF/1000000 "A)"; else print $1/1000 "mA)"}' $CURR_UNLIMIT_FILE)
            logdate "Charging settled at $LINE_VOLT / $CURR $CURR_UNLIMIT_TEXT" >> $BCC_LOG
            SETTLED=true
            
        elif $IS_PAUSED
            then # pause charging
            echo $PAUSE > $CURR_LIMIT_FILE
            if [[ $TEMP -le $RESUME_TEMP ]]
                then # resume charging
                logdate "Resuming at ${RESUME_TEMP}°C" >> $BCC_LOG
                IS_PAUSED=false
                unset $PAUSED_TEXT
            fi
            
        else
            # adjust current
            echo $CURRENT_LIMIT > $CURR_LIMIT_FILE
        fi
        
        if $SHOW_STATUS
            then # show status notification
            BATT_VOLT=$(awk '{printf "%0.2f\n",$1/1000000}' $BATT_VOLT_FILE)
            termux-notification --alert-once \
            --ongoing -i bcc \
            -t "${MODE}charging at $LINE_VOLT / $CURR $CURR_UNLIMIT_TEXT" \
            -c "Battery is ${LEVEL}% charged to ${BATT_VOLT}v and is at ${TEMP}°C ${PAUSED_TEXT}" \
            --button1 "${BUTTON1_TEXT}" \
            --button1-action "${BUTTON1_ACTION}" \
            --button2 "Hide Status" \
            --button2-action "su  -c 'pkill -l HUP -f $0'"
        fi
        
        if [[ $TEMP -ge $PAUSE_TEMP ]] && ! $IS_PAUSED
            then # pause charging
            IS_PAUSED=true
            logdate "Charging paused at $LEVEL% / ${TEMP}°C" >> $BCC_LOG
            PAUSED_TEXT="(paused at ${PAUSE_TEMP}°C)"
        fi
        
        if [[ $LEVEL -ge $STOP_LEVEL ]]
            then # stop charging
            echo $OFF > $CHARGE_FILE
            IS_DISABLED=true
            SHOW_WARNING=false
            set_cycle
            sleep 1
        else
            # connected, charging
            sleep $SLEEP_SHORT
        fi
        
    elif $WAS_CHARGING
        then # charging just stopped
        LEVEL_UP=$(($LEVEL-$LEVEL_INIT))
        TIME=$(date +%s)
        TIME_SPENT=$(($TIME-$TIME_INIT))
        TIME_SPENT=$(date -ud "@$TIME_SPENT" +'%Hh:%Mm')
        if [[ $STOP_LEVEL -ne 100 ]] && [[ $LEVEL -ge $STOP_LEVEL ]]
            then
            set_cycle
            TEXT="Charging is limited to ${STOP_LEVEL}%"
            BUTTON_TEXT="$BUTTON1_TEXT"
            BUTTON_ACTION="$BUTTON1_ACTION"
            logdate "Charging limited at $LEVEL%" >> $BCC_LOG
        else
            unset TEXT BUTTON_TEXT BUTTON_ACTION
            logdate "Charging stopped at $LEVEL% / ${TEMP}°C" >> $BCC_LOG
        fi
        termux-notification -i bcc \
            -t "Charged additional ${LEVEL_UP}% in $TIME_SPENT" \
            -c "$TEXT" \
            --button1 "${BUTTON_TEXT}" \
            --button1-action "${BUTTON_ACTION}"
        INIT=true
        SHOW_STATUS=true
        WAS_CHARGING=false
        
    elif [[ $LEVEL -lt $RESUME_LEVEL ]] && $IS_DISABLED
        then # re-enable charging
        echo $ON > $CHARGE_FILE
        IS_DISABLED=false
        logdate "Charging re-enabled at $LEVEL%" >> $BCC_LOG
        sleep 1
        
    elif [[ $LEVEL -ge $STOP_LEVEL ]] && ! $IS_DISABLED
        then # disable charging
        echo $OFF > $CHARGE_FILE
        IS_DISABLED=true
        SHOW_WARNING=false
        logdate "Charging disabled at $LEVEL%" >> $BCC_LOG
        sleep 1
        
    elif [[ $LEVEL -ge $RESUME_LEVEL ]] && $IS_DISABLED
        then # show warning
        ONLINE=$(cat $ONLINE_FILE)
        if [[ $ONLINE -gt 0 ]] && [[ $LEVEL -ne 100 ]] && $SHOW_WARNING
            then # charger just connected
            vibrate 2
            TEXT="Charging is suspended above ${RESUME_LEVEL}%"
            termux-notification -i bcc \
            -t "$TEXT" \
            --button1 "${BUTTON1_TEXT}" \
            --button1-action "${BUTTON1_ACTION}"
            SHOW_WARNING=false
            unset TEXT
        elif [[ $ONLINE == 0 ]] && ! $SHOW_WARNING
            then # charger just removed
            SHOW_WARNING=true
        else
            # above minimum, not charging
            logdate "Level $LEVEL% is above $RESUME_LEVEL%. Disabled, Not charging" >> $BCC_LOG
            while grep -qw $ONLINE $ONLINE_FILE
                do sleep $SLEEP_SHORT
            done
        fi
        
    else
        # not connected, not charging
        logdate "Level is $LEVEL%. Not connected" >> $BCC_LOG
        ONLINE=$(cat $ONLINE_FILE)
        while grep -qw $ONLINE $ONLINE_FILE
                do sleep $SLEEP_SHORT
        done
    fi
done
}

daemon_start () {
    echo -n "Starting Basic Charging Control "
    if kill-process $0 $PID_FILE check-only
        then
        PID=$(cat $PID_FILE)
        echo "(PID: $PID) $(SKIP)"
    else
        logdate "Starting Basic Charging Control" > $BCC_LOG
        echo $ON > $CHARGE_FILE
        set_cycle
        daemon_run &> /dev/null &
        PID=$!
        echo $PID > $PID_FILE
        echo "(PID: $PID) $(DONE)"
    fi
}

daemon_status () {
    echo -n "Basic Charging Control is "
    if kill-process $0 $PID_FILE check-only
        then
        PID=$(cat $PID_FILE)
        echo "running (PID: $PID) $(OK)"
    else
        echo "not running $(FAIL)"
    fi
}

daemon_stop () {
    PID=$(cat $PID_FILE 2> /dev/null)
    echo -n "Stopping Basic Charging Control "
    if kill-process $0 $PID_FILE
        then
        echo $ON > $CHARGE_FILE
        echo "(PID: $PID) $(DONE)"
    else
        SKIP
    fi
}

# main ()

case $1 in
    start)
        daemon_start
        ;;
    status)
        daemon_status
        ;;
    restart)
        daemon_stop
        daemon_start
        ;;
    stop)
        daemon_stop
        ;;
    *)
        echo "Usage: start | status | restart | stop"
        ;;
esac

