#!/data/bin/bash

## Update busybox compiled by osm0sis
## Author: Seff P
## Version: 1.0.1 20210620

source check-root
source set-dir
source set-prompt

APP_DN="Busybox"
APP_NAME="busybox"
APP_URL="https://raw.githubusercontent.com/Magisk-Modules-Repo/busybox-ndk/master/busybox-arm64-selinux"
INSTALL_DIR="/data/bin"
UPDATED=false
CURL="/system/bin/curl"

check () {
    echo -n "Checking for ${APP_DN} update "
    CUR_BYTES=$(cat ${VAR}/${APP_NAME}_bytes)
    NEW_BYTES=$($CURL -Is --insecure --connect-timeout 5 ${APP_URL}  | busybox awk 'BEGIN{IGNORECASE=1} /Content-Length/ {printf $2}')
    if [[ "$CUR_BYTES" == "$NEW_BYTES" ]]
        then OK
        date > ${VAR}/${APP_NAME}-update.last_checked
        return 2
    elif [ -z "$NEW_BYTES" ]
        then FAIL
        return 1
    else
        date > ${VAR}/${APP_NAME}-update.last_checked
        UPDATED
    fi
}
  
download () {
    echo -ne "Downloading update "
    if $CURL --insecure -s ${APP_URL} -o $BIN/${APP_NAME}.tmp
    then
        mv -f $BIN/${APP_NAME}.tmp $BIN/${APP_NAME}
        echo -n $NEW_BYTES > ${VAR}/${APP_NAME}_bytes
        UPDATED=true
        DONE
    else
        FAIL
        rm -f $BIN/${APP_NAME}.tmp
        return 1
    fi
 }

apply () { 
    if $UPDATED
        then
        cp -f $BIN/${APP_NAME} $INSTALL_DIR/
        /system/bin/chmod +x $INSTALL_DIR/${APP_NAME}
        $INSTALL_DIR/busybox --install -s $INSTALL_DIR
        NEW_VER=$($INSTALL_DIR/busybox | awk '{print $2; exit}')
        termux-notification -t "${APP_DN} updated to $NEW_VER" -c "" --id ${APP_NAME}
        echo "Updating ${APP_DN} to $NEW_VER $(DONE)"
    else
        SKIP
    fi
}

case $1 in
 "")
    check && download && apply
    ;;
 *)
    echo "Download and install latest ${APP_DN}"
    ;;
esac