#!/data/bin/bash

## Check current user is root or not
## Author: Seff P
## Version: 20191206

source set-prompt

if [[ $(id -u) -ne 0 ]]
 then echo "Checking root access $(FAIL)"
 # vibrate
 exit 1
fi