#!/data/bin/bash

## Check current user is root or not
## Author: Seff P
## Version: 20191206

source set-color

if ! [ $(id -u) == "0" ]
 then echo -e "${R}ERROR: Root privilege required!${W}"
 # vibrate
 exit 1
fi