#!/data/bin/bash

## Daily routine tasks
## Author: Seff P
## Version: 2.1.0 20210215

source check-root
source set-dir
source set-prompt

DATE_LOG="$LOG/daily-jobs.history"
OUTPUT_LOG="$LOG/daily-jobs.log"
PREV_PID_FILE="$RUN/daily-jobs.pid-previous"
BUCKET="$VAR/status-widget/bucket/daily-jobs"
IS_ONLINE=false
ONLINE=offline
NET_WAIT=15
JOB=1 # Index of first job
N=6 # Total no. of jobs

# functions
notify () {
    timeout 2 termux-notification --ongoing --id dailyjobs --title "Running daily jobs: $1/$N" --content "$2"
}

prepare () {
    cp -f $OUTPUT_LOG ${OUTPUT_LOG}.previous
    exec &> >(logdate | tee "$OUTPUT_LOG")
    echo -e "daily-jobs $(BEGIN)"
    PREV_PID=$(cat $PREV_PID_FILE 2> /dev/null)
    echo $$ > $PREV_PID_FILE
    busybox pkill -9 -P $PREV_PID &> /dev/null
    busybox pkill -9 $PREV_PID &> /dev/null
    echo -en "Holding wake-lock "
    termux-wake-lock
    vibrate 1
    sleep 1
    DONE
    termux-api-clean
    notify 0 "Preparing..."
    echo "SHELL=$BASH $BASH_VERSION"
    uptime
    check-ping && IS_ONLINE=true && ONLINE=online
    
    if ! tty -s && ! $IS_ONLINE
        then
        notify 0 "Waiting $NET_WAIT seconds for Internet..."
        echo "Waiting $NET_WAIT seconds for Internet"
        vibrate 3
        sleep $NET_WAIT
        check-ping && IS_ONLINE=true && ONLINE=online
        fi
    
}

run_jobs () {
    if $IS_ONLINE
        then
        notify $JOB "Checking adblock update..."
        adblock update
    fi
    ((JOB++))

    if $IS_ONLINE
        then
        notify $JOB "Checking APK updates..."
        apk-update -u
    fi
    ((JOB++))
    
    notify $JOB "Optimizing memory & cache..."
    optimize-cache
    optimize-memory
    ((JOB++))
    
    notify $JOB "Generating maintenance report..."
    apt-update report
    backup-sdcard report
    optimize-db report
    ((JOB++))
    
    notify $JOB "Detaching apps from PlayStore..."
    detach-from-playstore --pre-def
    ((JOB++))
}

finish () {
    notify $JOB "Finishing up..."
    sed -i 1d $DATE_LOG
    echo "$(logdate) IS_ONLINE=$IS_ONLINE" >> $DATE_LOG
    echo "Daily Jobs ran $ONLINE at $(date +"%l:%M %p")" > $BUCKET
    echo -e "daily-jobs $(DONE)"
    echo -en "Releasing wake-lock "
    termux-notification-remove dailyjobs
    termux-wake-unlock
    sleep 0.1
    DONE
}

# main
prepare
run_jobs
finish