#!/data/bin/bash

## Detatch given apps from PlayStore
## Author: Seff P
## Version: 20200910

source set-dir
source set-color

PLAY_DB_DIR="/data/data/com.android.vending/databases"

doDetach () {
    for PKG_URI in $*
    do
    	echo -n "$(logdate) Detaching $PKG_URI "
    	CHECK=$(sqlite3 $PLAY_DB_DIR/library.db "SELECT doc_id FROM ownership WHERE doc_id = '$PKG_URI'";)
    
    	if [ -z "$CHECK" ]
    	then
    	    SKIP
    	else
    	    sqlite3 $PLAY_DB_DIR/library.db "DELETE from ownership where doc_id = '$PKG_URI'";
    	    sqlite3 $PLAY_DB_DIR/localappstate.db "DELETE from appstate where package_name ='$PKG_URI'";
    	    DETACHED=true
    	    DONE
    	fi
    done
    doCleanUp
}

doCleanUp () {
	if [[ "$DETACHED" ]]
		then
		echo -n "$(logdate) Performing cleanup "
		setenforce 0
		/system/bin/am force-stop com.android.vending
		setenforce 1
		DONE
	fi
}

case $1 in
  --pre-def)
    doDetach $(cat $ETC/detach.list)
    ;;
  "")
    echo "Usage: $(basename $0) [PKG_URIs | --pre-def]"
	exit 2
    ;;
  *)
    doDetach $*
    ;;
esac