#!/data/bin/bash

## Update App from given APK file URL
## Author: Seff P.
## Version: 20201214

source set-dir
source set-prompt

ASSET_URL="https://androidapksfree.com/es-file-manager/com-estrongs-android-pop/download/"
APK_PATH="/sdcard/Backups/apps"
PKG_ID="com.estrongs.android.pop"
PKG_NAME="ES Explorer"
APK_URL="$VAR/$PKG_ID.url"
TMP="/data/local/tmp/"
BUCKET="$VAR/status-widget/bucket/es-explorer"

checkUpdate () {
    echo -n "Checking ${PKG_NAME} update "
    APK_URL_OLD=$(cat $APK_URL 2> /dev/null)
    APK_URL_NEW=$(/system/bin/curl -sk --connect-timeout 5 -m 10 $ASSET_URL | grep -o "https.*\.apk")
    if [[ "$APK_URL_NEW" == "$APK_URL_OLD" ]]
        then OK
        return 2
    elif [[ -z $APK_URL_NEW ]]
        then FAIL
        return 1
    else
        APK_NAME=$(basename $APK_URL_NEW)
        termux-notification --title "${PKG_NAME} update available" --content "$APK_NAME" --id $PKG_ID
        UPDATED
        return 0
    fi
}

installUpdate () {
    PKG_VERSION_CURR=$(dumpsys package $PKG_ID | awk -F "=" '/versionName/ {print $2}')
    echo "Current version: $PKG_VERSION_CURR"
    echo "Downloading $PKG_NAME update..."
    echo $APK_PATH/$APK_NAME
    wget -c -t 0 -T 10 $APK_URL_NEW -O $APK_PATH/$APK_NAME
    echo "Updating ${PKG_NAME} $(BEGIN)"
    cp -f $APK_PATH/$APK_NAME $TMP/
    if pm install -f $TMP/$APK_NAME
        then
        echo $APK_URL_NEW > $APK_URL
        PKG_VERSION_NEW=$(dumpsys package $PKG_ID | awk -F "=" '/versionName/ {print $2}')
        termux-notification --title "${PKG_NAME} is successfully updated" \
        --content "from version $PKG_VERSION_CURR to $PKG_VERSION_NEW" --id $PKG_ID
        echo "Updated version: $PKG_VERSION_NEW"
        echo "$PKG_NAME updated to version $PKG_VERSION_NEW" > $BUCKET
        echo "Updating ${PKG_NAME} $(DONE)"
    else
        termux-notification --title "${PKG_NAME} update failed" --id $PKG_ID
        echo "Updating ${PKG_NAME} $(FAIL)"
    fi
    rm -f $TMP/$APK_NAME
}

case $1 in
    -c | c* )
        checkUpdate
        ;;
    -u | u* )
        check-root && \
        checkUpdate && \
        installUpdate
        ;;
    *)
        echo "Usage: -c|check | -u|update"
        exit 1
        ;;
esac