#!/data/bin/bash

## Update App from given APK file URL
## Author: Seff P.
## Version: 20200803

source check-root
source check-ping
source set-dir
source set-color

ASSET_URL="http://estrongs.com/js/app.2424545d.js"
APK_PATH="/sdcard/Backups/apps/com.estrongs.android.pop.apk"
PKG_ID="com.estrongs.android.pop"
PKG_NAME="ES Explorer"
APK_URL="$VAR/$PKG_ID.url"


checkUpdate () {
    echo -n "$(logdate) Notify ${PKG_NAME} update "
    APK_URL_OLD=$(cat $APK_URL 2> /dev/null)
    APK_URL_NEW=$(curl -sk --connect-timeout 2 --retry 5 -m 10 $ASSET_URL | grep -o "http.*\.apk")
    if [[ "$APK_URL_NEW" == "$APK_URL_OLD" ]]
        then SKIP
        return 2
    elif [[ -z $APK_URL_NEW ]]
        then FAIL
        return 1
    else
        termux-notification --title "${PKG_NAME} update available" --id apk-update
        DONE
        return 0
    fi
}

installUpdate () {
    PKG_VERSION=$(dumpsys package $PKG_ID | awk -F "=" '/versionName/ {print $2}')
    echo "$(logdate) Current version: $PKG_VERSION"
    echo "$(logdate) Downloading $PKG_NAME update..."
    mv $APK_PATH ${APK_PATH}_${PKG_VERSION}
    wget -t 0 -T 10 $APK_URL_NEW -O $APK_PATH
    echo "$(logdate) Updating ${PKG_NAME} $(BEGIN)"
    setenforce 0
    pm install -f $APK_PATH
    setenforce 1
    echo "$(logdate) Updating ${PKG_NAME} $(DONE)"
    echo $APK_URL_NEW > $APK_URL
    PKG_VERSION=$(dumpsys package $PKG_ID | awk -F "=" '/versionName/ {print $2}')
    echo "$(logdate) Updated version: $PKG_VERSION"
}

case $1 in
    -c | c* )
        checkUpdate
        ;;
    -u | u* )
        checkUpdate && installUpdate
        ;;
    *)
        echo "Usage: -c|check | -u|update"
        exit 1
        ;;
esac