#!/data/bin/bash

# Print file modification age in different units
# Author: Seff Parker
# Version: 0.0.2 20210711

QUIET_UNIT=false

UNIT_s="second"
UNIT_m="minute"
UNIT_h="hour"
UNIT_d="day"
UNIT_M="month"
UNIT_y="year"

age_second () {
    AGE=${AGE_SEC}
}

age_minute () {
    AGE=$(((${AGE_SEC}+15)/60))
}

age_hour () {
    AGE=$(((${AGE_SEC}+600)/3600))
}

age_day () {
    AGE=$(((${AGE_SEC}+7200)/86400))
}

age_month () {
    AGE=$(((${AGE_SEC}+259200)/2592000))
}

age_year () {
    AGE=$(((${AGE_SEC}+2592000)/31104000))
}

age_auto () {
    if [[ ${AGE_SEC} -lt 60 ]]
        then
        UNIT="second"
    elif [[ ${AGE_SEC} -lt 3600 ]]
        then
        UNIT="minute"
    elif [[ ${AGE_SEC} -lt 86400 ]]
        then
        UNIT="hour"
    elif [[ ${AGE_SEC} -lt 2592000 ]]
        then
        UNIT="day"
    elif [[ ${AGE_SEC} -lt 31104000 ]]
        then
        UNIT="month"
    else
        UNIT="year"
    fi
    age_${UNIT}
}

process_file () {
    FILE=$1
    if [[ -f ${FILE} ]] || [[ -d ${FILE} ]]
        then
        FILE_DATE=$(date +%s -r ${FILE})
        CURR_DATE=$(date +%s)
        let AGE_SEC=${CURR_DATE}-${FILE_DATE}
    elif [ -z $FILE ]
        then print_usage
    else
        echo "ERROR: Cannot open file at '$FILE'"
        exit 1
    fi
}

process_string () {
    STRING=$1
    if STRING_DATE=$(date +%s -d "${STRING}")
        then
        CURR_DATE=$(date +%s)
        let AGE_SEC=${CURR_DATE}-${STRING_DATE}
    else
        echo "ERROR: Couldn't process date string '$STRING'"
        exit 1
    fi 
}

process_unit () {
    UNIT_VAR=UNIT_${UNIT_ARG}
    UNIT=${!UNIT_VAR:=auto}
}

print_usage () {
    echo "Usage: $(basename $0) [-u UNIT] [-q] [-f] filename"
    echo
    echo "   -f       Path to file / dir"
    echo "             or STDIN date string"
    echo "   -u UNIT  Unit to calculate:"
    echo "             s = second"
    echo "             m = minute"
    echo "             h = hour"
    echo "             d = day"
    echo "             M = month"
    echo "             y = year"
    echo "   -q        Quiet, hide unit"
    exit 2
}

while getopts ":u:qf:" OPT; do
case ${OPT} in
    u)
        UNIT_ARG=${OPTARG}
        ;;
    q)
        QUIET_UNIT=true
        ;;
    f)
        FILE=${OPTARG}
        ;;
    *)
        print_usage
        ;;
    esac
done

if [[ -p /dev/stdin ]]
    then
    STRING=$(cat -)
    process_string "$STRING"
else
    process_file ${FILE:=$BASH_ARGV}
fi
process_unit

if [[ $AGE_SEC ]]
    then
    age_${UNIT}
    echo -n $AGE
    if ! ${QUIET_UNIT}
        then
        [[ $AGE -gt 1 ]] && S="s"
        echo " ${UNIT}${S}"
    fi
else
    print_usage
fi