#!/data/bin/bash

## Optimize Android app databases
## Author: Seff P
## Version: 1.0.3 20210703

source set-dir
source set-prompt
source $ETC/optimize-db.conf
BUCKET="$VAR/status-widget/bucket/optimize-db"
BIN_DEPS="sqlite3"

 case $1 in
 -r|r*)
    OPTIMIZE_DB_AGE=$(get-file-age -qu d $VAR/optimize-db.last_run)
    OPTIMIZE_DB_AGO=$(get-file-age $VAR/optimize-db.last_run)
    if [ $OPTIMIZE_DB_AGE -gt $REMIND_DAYS ]
    then
        termux-notification --title "Database is not optimized recently!" --content "Last optimized $OPTIMIZE_DB_AGO ago" --icon warning
        echo "Databases last optimized $OPTIMIZE_DB_AGO ago" > $BUCKET
        
    fi
    echo "Databases last optimized $OPTIMIZE_DB_AGO ago"
    ;;

 -o|o*)
    source check-root
    source check-bin $BIN_DEPS
    PRESIZE=0
    POSTSIZE=0
    termux-wake-lock
    /system/bin/svc data disable
    /system/bin/svc wifi disable
    LD_PRELOAD=""
    for DB in \
    $(busybox find /data/data/*/databases \
        -type f  ! -name "*-shm" \
        ! -name "*-wal" ! -name "*-journal");
    do \
        CURSIZE=$(du $DB | awk {'print $1'})
        PRESIZE=$(( $PRESIZE + $CURSIZE ))
        echo -n ""
        echo "$DB" | awk -F '/' '{printf $4" - "$6}'
        if sqlite3 $DB 'REINDEX;' &> /dev/null
            then
            sqlite3 $DB 'VACUUM;' &> /dev/null
            DONE
        else
            FAIL
        fi
        CURSIZE=$(du $DB | awk {'print $1'})
        POSTSIZE=$(( $POSTSIZE + $CURSIZE ))
    done;

    date > $VAR/optimize-db.last_run
    echo "Databases last optimized on $(date +%F)" > $BUCKET
    echo
    echo "Total DB size before: $PRESIZE KB"
    echo "Total DB size after : $POSTSIZE KB"
    echo "_____"
    echo "Vacuumed size       : $(($PRESIZE - $POSTSIZE)) KB"
    termux-wake-unlock
    ;;
    
    *)
    echo "Usage: $(basename $0) [-r|report | -o|optimize]"
    ;;
esac