#!/data/bin/bash

## Optimize system RAM
## Author: Seff P
## Version: 20191129

source check-root
source set-prompt

echo -ne "Saving buffers "
    sync
    DONE

echo -ne "Dropping caches "
    echo 1 > /proc/sys/vm/drop_caches
    DONE

echo -ne "Compacting memory "
    echo 1 > /proc/sys/vm/compact_memory
    DONE