#!/data/bin/bash

## Copy songs from a playlist
## Author: Seff P
## Version: 20200703

source check-root
source termux-env
source set-color

PLS_DIR="/sdcard/Playlists"

DESTS="/sdcard/_TEMP_of_ROOT/pls-to-file/"

cd $PLS_DIR
echo "Choose a playlist to sync:"
select PLS in *.m3u8
    do [[ -f $PLS ]] && break
    done
    
echo "Choose a destination:"
select DEST in ${DESTS} $(ls -d /mnt/media_rw/*/ 2> /dev/null)
    do
    mkdir -p $DEST
    if [ -d "$DEST" ]
        then break
    else
        echo "Destination $DEST doesn't exists"
    fi
    done

echo "Enter a custom subdirectory:"
read SUB_DIR
mkdir -p $DEST/$SUB_DIR

echo "Copying songs to $DEST"
rsync -v --files-from="${PLS}" / $DEST/$SUB_DIR && DONE || FAIL