#!/data/bin/bash

## Post boot tasks
## Author: Seff P
## Version: 20201002

# Preparing
source check-root
source set-dir
source $ETC/bashrc.root
source $ETC/hostname
source $ETC/dns
export BG=true

BUCKET="$VAR/status-widget/bucket/boot"

# Logs
DATE_LOG="${LOG}/post-boot.history"
sed -i 1d $DATE_LOG
[ $1 ] && MODE="$1" || MODE="manual trigger"
echo "$(logdate) $MODE" >> $DATE_LOG

# Begin
echo SHELL=$SHELL

echo -n "SELinux mode (session): "
    setenforce 0
    getenforce

# Fast entropy
echo -ne "Optimizing entropy  "
if [[ -e /dev/random_default ]]
    then
    echo [SKIP]
else
    mv /dev/random /dev/random_default
    ln /dev/urandom /dev/random
    mv /dev/hw_random /dev/hw_random_default
    ln /dev/urandom /dev/hw_random
    echo [DONE]
fi

# I/O scheduler
echo -ne "I/O scheduler tweak  "
for DEVICE in /sys/block/sd*/queue /sys/block/dm-0/queue
    do echo noop > $DEVICE/scheduler
    echo 64 > $DEVICE/read_ahead_kb
    done
echo [DONE]

echo "Locking vault"
    vault 1

echo -n "Setting hostname $HOSTNAME  "
if [[ "$(hostname)" == "$HOSTNAME" ]]
    then echo "[SKIP]"
else
    /system/bin/hostname $HOSTNAME
    echo "[DONE]"
fi

echo -n "Disabling loggings  "
    stop logd
    settings put global dropbox_max_files 0
    echo "[DONE]"

echo -n "DNS tweak via $CUSTOM_DNS  "
    if iptables -t nat -L | grep -q "${CUSTOM_DNS}:53"
        then echo "[SKIP]"
    else
        iptables -t nat -I OUTPUT -p udp --dport 53 -j DNAT --to-destination ${CUSTOM_DNS}:53
        echo "[DONE]"
    fi

echo -ne "(Re)starting crond "
    pkill -9 crond &> /dev/null
    /data/bin/crond -c $ETC/crontabs
    echo "(PID: $(pidof crond))  [DONE]"
    
basic-charging-control start
system-monitor start
status-widget start

setenforce 1

if [[ "$1" ]]
    then
    termux-notification --content "Boot scripts are completed!" --id post-boot
    echo "$HOSTNAME ignition at $(date +"%b %e, %a %l:%M %p" -r /storage)" > $BUCKET
    vibrate 1
fi