#!/data/bin/bash

source check-root
source set-color

echo -n "Mounting as RW "
for FS in / /sbin/.magisk/mirror/system /sbin/.magisk/mirror/vendor
    do
    /system/bin/mount -o remount,rw $FS
   done
   
if touch /write_check &> /dev/null
    then
    DONE
else
    FAIL
    exit 1
fi