#!/data/bin/bash

source check-root
source set-color

echo -n "Mounting as RO "
for FS in / /sbin/.magisk/mirror/system /sbin/.magisk/mirror/vendor
    do
    /system/bin/mount -o remount,ro $FS
   done
DONE