#!/data/bin/bash

source check-root
source set-color

/system/bin/mount -o remount,rw /vendor
/system/bin/mount -o remount,rw /system
/system/bin/mount -o remount,rw /

if ! touch /write_check
 then
 echo -e "${R}ERROR: Failed to mount as RW!${W}"
 exit 2
fi