#!/data/bin/bash

## Generate various reports
## Author: Seff P
## Version: 2.0.1 20210703

check-root &> /dev/null || exec /sbin/su -c 'report'
source set-dir
source termux-env

echo -ne "$HOSTNAME engine start:\t"
BTIME=$(awk '/btime/ {print $2}' /proc/stat)
date -d @${BTIME} 2> /dev/null || echo UNKNOWN

echo -ne "Load average:\t\t"
cat /proc/loadavg | cut -d' ' -f1-3

echo -ne "Last run of post-boot:\t"
date -r $LOG/post-boot.history 2> /dev/null || echo UNKNOWN

echo -ne "Last run of daily-jobs:\t"
date -r $LOG/daily-jobs.history 2> /dev/null || echo UNKNOWN

echo -ne "APT update date:\t"
date -r /data/data/com.termux/files/usr/var/log/apt/history.log 2> /dev/null || echo UNKNOWN

echo -ne "Adblock database date:\t"
date -d "$(grep '# Date:' /etc/hosts | cut -d' ' -f3-7)" 2> /dev/null || echo UNKNOWN

crond-service status
system-monitor status
status-widget status
basic-charging-control status