#!/data/bin/bash

## Generate various reports
## Author: Seff P
## Version: 20201106

check-root &> /dev/null || exec /sbin/su -c 'report'
source set-dir
source termux-env

echo -ne "$HOSTNAME engine start:\t"
date -r /storage 2> /dev/null || echo UNKNOWN

echo -ne "Last run of post-boot:\t"
date -r $LOG/post-boot.history 2> /dev/null || echo UNKNOWN

echo -ne "Last run of daily-jobs:\t"
date -r $LOG/daily-jobs.history 2> /dev/null || echo UNKNOWN

echo -ne "APT update date:\t"
date -r /data/data/com.termux/files/usr/var/log/apt/history.log 2> /dev/null || echo UNKNOWN

echo -ne "Adblock database date:\t"
date -d "$(grep '# Date:' /etc/hosts | cut -d' ' -f3-7)" 2> /dev/null || echo UNKNOWN

echo -ne "crond service status:\t"
pgrep crond &> /dev/null && echo "RUNNING (PID: $(pidof crond))" || echo STOPPED

echo -ne "BCC service status:\t"
pgrep -f basic-charging-control &> /dev/null && echo "RUNNING (PID: $(cat $RUN/bcc.pid))" || echo STOPPED

echo -ne "Load average:\t\t"
cat /proc/loadavg | cut -d' ' -f1-3