#!/data/bin/bash

# Generate plain HTML file from text file
# Author: Seff Parker
# Version: 20210109 v0.0.1

source set-prompt
source set-dir

APP_NAME="Status Widget"
PID_FILE="$RUN/status-widget.pid"
BUCKET="$VAR/status-widget/bucket"
HTML="$VAR/status-widget/html/status-widget"
NGX_CONF="$ETC/nginx/status-widget.conf"
INTERVAL=10

daemon_run () {
    nginx -c $NGX_CONF
    while true
        do
        HASH=$(stat -c %y $BUCKET/* | md5sum)
        if [[ "$HASH" != "$HASH_PREV" ]]
        then
            echo "<html><body>" > $HTML
            for ITEM in $(ls -t $BUCKET)
                do
                echo "<p>"
                cat $BUCKET/$ITEM
                echo "</p>"
            done >> $HTML
            echo "</body></html>" >> $HTML
            HASH_PREV=$HASH
        fi
        sleep $INTERVAL
    done
}

daemon_start () {
    echo -n "Starting ${APP_NAME} "
    if start-stop-daemon -Ktq -p $PID_FILE &> /dev/null
        then
        PID=$(cat $PID_FILE)
        echo "(PID: $PID) $(SKIP)"
    else
        start-stop-daemon -S -m -p $PID_FILE -b $0 -- run
        PID=$(cat $PID_FILE)
        echo "(PID: $PID) $(DONE)"
    fi
}

daemon_status () {
    echo -n "${APP_NAME} is "
    if start-stop-daemon -Ktq -p $PID_FILE &> /dev/null
        then
        PID=$(cat $PID_FILE)
        echo "running (PID: $PID) $(OK)"
    else
        echo "not running $(FAIL)"
    fi
}

daemon_stop () {
    PID=$(cat $PID_FILE 2> /dev/null)
    echo -n "Stopping ${APP_NAME} "
    nginx -s stop -c $NGX_CONF
    if start-stop-daemon -Kq -p $PID_FILE -s 9
        then
        rm -f $PID_FILE
        echo "(PID: $PID) $(DONE)"
    else
        SKIP
    fi
}

# main ()

case $1 in
    start)
        daemon_start
        ;;
    run)
        daemon_run
        ;;
    status)
        daemon_status
        ;;
    restart)
        daemon_stop
        daemon_start
        ;;
    stop)
        daemon_stop
        ;;
    *)
        echo "Usage: start | status | restart | stop"
        ;;
esac