#!/data/bin/bash

## Sync user scripts to system path
## Author: Seff P
## Version: 20191129

# Preparation
source check-root

source set-dir
source set-color

echo -ne "Updating custom scripts "
rsync -ru --inplace $XBIN/* /data/xbin/ --chmod=755 --chown=root:shell && DONE || FAIL