#!/data/bin/bash

## Manage Vanced version of YouTube
## Author: Seff P
## Version: 20200826

source check-root
source set-color
source set-dir

PKG_ID="com.google.android.youtube"
PKG_DATA_DIR="/data/data/com.google.android.youtube"
PKG_APP_DIR="$BINDS//YouTube"
PKG_DATA_BACKUP="$VAR/youtube-vanced.settings.tar"
PKG_USER=$(stat -c %U $PKG_DATA_DIR)

DetachYoutube() {
    detach-from-playstore $PKG_ID
}

RestoreYoutubeApp() {
if ls -d /data/app/$PKG_ID-* &> /dev/null
    then
    echo -n "$(logdate) Uninstalling $PKG_DN updates "
    setenforce 0
    pm uninstall -k $PKG_ID
    setenforce 1
    tar -xf $PKG_DATA_BACKUP -C /
    termux-run termux-notification --content "Uninstalled $PKG_DN updates"
    DONE
    RestoreYoutubeData
fi
}

RestoreYoutubeData() {
    echo -n "$(logdate) Restoring YouTube settings  "
    tar -xf $PKG_DATA_BACKUP -C /
    chown -hR $PKG_USER:$PKG_USER $PKG_DATA_DIR
    DONE
}

BackupYoutubeData() {
    echo -n "$(logdate) Backing up YouTube data  "
    tar -cf $PKG_DATA_BACKUP $PKG_DATA_DIR/databases $PKG_DATA_DIR/shared_prefs
    DONE
}

case $1 in
 -d|d*)
    DetachYoutube
    ;;
    
 -u|u*)
    DetachYoutube
    RestoreYoutubeApp
    ;;
    
 -b|b*)
    BackupYoutubeData
    ;;
    
 -r|r*)
    RestoreYoutubeData
    ;;
    
 *)
    echo "Usage: $(basename $0) [-d|detach | -u|uninstall updates | -b|backup | -r|restore]"
    ;;
esac